### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by egfrazier** [monodokimes/pythonmon#2]
After changing the filename to lowercase to resolve issue "#1 ImportErrors" that seemed to resolve it. I tried to run the engine again, it keeps erroring out after selecting Run Game on the Main Menu:

```
File "C:\pc_projects\pythonmon\scenemodule.py", line 16, in __init__
    entity = entity.Entity(entity_data["Name"], position)
UnboundLocalError: local variable 'entity' referenced before assignment
```

Maybe a naming conflict between a variable named 'entity' in the scenemodule.py and the module named 'entity'?

**Comment by ktyldev** [comment]
That was exactly the problem, I fixed this issue as well as a couple of other similar issues along with the ImportError issue you also reported. Thanks! :D
